parameters:
#    mcm_demo.example.class: MCM\DemoBundle\Example

services:
#    mcm_demo.example:
#        class: %mcm_demo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
